spring:
  port: 8080
  dubbo:
    name: provider2
    address: zookeeper://127.0.0.1:2181
    protocol:
      name: dubbo
      port: 20880
      scan: com.spring.springboot.service
      
jdbc:
  database:
    master:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://127.0.0.1:3306/test
      username: root
      password: 1234
      maxActive: 139
      driverClass: com.mysql.cj.jdbc.Driver
    slave1:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://127.0.0.1:3306/test
      username: root
      password: 1234
      maxActive: 139
      driverClass: com.mysql.cj.jdbc.Driver
    slave2:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://127.0.0.1:3306/test
      username: root
      password: 1234
      maxActive: 139
      driverClass: com.mysql.cj.jdbc.Driver
    config:
      slavenum: 2
      
kabc:
  type: com.alibaba.druid.pool.DruidDataSource
  url: jdbc:mysql://127.0.0.1:3306/test
  jdbc-url: jdbc:mysql://127.0.0.1:3306/test
  jdbcUrl: jdbc:mysql://127.0.0.1:3306/test
  username: root
  password: 1234
  maxActive: 139
  driverClass: com.mysql.cj.jdbc.Driver

redis: 
  host: localhost
  port: 6379

#tomcat
server:
  tomcat:
    max-connections: 20000
    max-threads: 10000
    
mybatis:
  # 包下所有类的别名
  type-aliases-package: top.linruchang.product_service.domain
  # dao层的sql映射路径
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    # 缓存开启
    cache-enabled: true
    # 懒加载开启
    lazy-loading-enabled: true
    # SQL打印日志所使用的日志类 - 关键
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl