spring:
  dubbo:
    name: provider2
    address: zookeeper://127.0.0.1:2181
    protocol:
      name: dubbo
      port: 20880
      scan: com.spring.springboot.service
  data:
    mongodb:
      uri: mongodb://192.168.1.2:27017/mymongo
      
jdbc:
  database:
    master:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://192.168.1.4:3306/test
      username: root
      password: 1234
      maxActive: 139
      driverClass: com.mysql.cj.jdbc.Driver
    slave1:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://192.168.1.4:3306/test
      username: root
      password: 1234
      maxActive: 139
      driverClass: com.mysql.cj.jdbc.Driver
    slave2:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://192.168.1.4:3306/test
      username: root
      password: 1234
      maxActive: 139
      driverClass: com.mysql.cj.jdbc.Driver
    config:
      slavenum: 2
      
kabc:
  type: com.alibaba.druid.pool.DruidDataSource
  url: jdbc:mysql://127.0.0.1:3306/test
  jdbc-url: jdbc:mysql://127.0.0.1:3306/test
  jdbcUrl: jdbc:mysql://127.0.0.1:3306/test
  username: root
  password: 1234
  maxActive: 139
  driverClass: com.mysql.cj.jdbc.Driver

redis: 
  host: localhost
  port: 6379

#tomcat
server:
  port: 8083
  tomcat: 
    max-connections: 20000
    max-threads: 1000
    accept-count: 20000
    min-spare-threads: 300

#server:
#  port: 8082
#  tomcat: 
#    uri-encoding: UTF-8
#    max-threads: 10000 #最大工作线程数量
#    min-spare-threads: 20 #最小工作线程数量
#    max-connections: 10000 #一瞬间最大支持的并发的连接数
#    accept-count: 200 #等待队列长度
    
